### PR TITLE
Methods for modifying map state

### PR DESCRIPTION
**Pull request by torhovland**

### CODE REVIEW

**Comment by flosse** [comment]
Would you mind to rebase this commit to have a clean history?
Otherwise I'd just cherry-pick this one.

**Comment by torhovland** [comment]
OK, done!

**Comment by flosse** [comment]
Thanks a lot!

**Comment by flosse** [comment]
... and let me know if you like to have new version published on crates.io

**Comment by torhovland** [comment]
Just publish when it suits you. In the meantime I just refer to my own fork as a dependency.

**Pull request merged**
